name = "consult-queue"
main = "worker.js"
compatibility_date = "2026-01-01"

[[durable_objects.bindings]]
name = "QUEUE"
class_name = "ConsultQueue"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ConsultQueue"]
